# Generated by Django 5.1.4 on 2024-12-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('teacher_name', models.CharField(max_length=100)),
                ('fees', models.IntegerField()),
                ('age', models.CharField(choices=[('age1', '2 to 5'), ('age2', '5 to 8'), ('age3', '8 to 10'), ('age4', '10 to 12')], max_length=20)),
                ('time', models.CharField(choices=[('batch1', '9 to 12'), ('batch2', '12 to 2'), ('batch3', '2 to 4')], max_length=20)),
                ('capacity', models.IntegerField()),
            ],
        ),
    ]
