# Generated by Django 5.1.4 on 2024-12-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('child_name', models.CharField(max_length=50)),
                ('child_age', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
